name: Update gist with Steam Playtime

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Update-gist
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: a46bced8040d821e1c50cf80390daf23
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_ID: ${{ secrets.STEAM_ID }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Initialize Go dependencies
        run: |
          go mod tidy
          go mod download

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Update-gist
        run: go run ./cmd/box/main.go
