name: Update gist with Steam Playtime

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: gist-update
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: f796e6cee5e4e074ba995e32c3ec9c1d
          GIST_ID_RECENT: 0ba0c711e56d940b84cac27f58b9e158
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Update-gist
      run:  go run ./cmd/box/main.go
